name: Comandos Workflows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mensajes de Warning y Error
        run: |
          echo "Un mensaje normal"
          echo "::warning::Mensaje de advertencia"
          echo "::error::Este es un mensaje de error"
