name: Expresiones ejemplo

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sistema_operativo: [windows-lates, ubuntu-latest, macos-latest]
    name: matris-unidimencional
    runs-on: ${{ matrix.sistema_operativo }}
    steps:
      - name: paso solo para windows
        if: ${{ matrix.sistema_operativo == 'windows-latest' }}
        run: echo "Esto solo se ejecuta en Windows"

      - name: paso para todos los SOs
        run: echo "Paso común para todos los sistemas operativos"
