name: hola mundo

on:
  workflow_dispatch: 
  # schedule:
  #   - cron: "*/5 * * * *" # se ejecuta cada 5 minutos
  push: 
     branches:
       - main
  pull_request:
    branches:
      - main

jobs: 
  saludar:
    runs-on: ubuntu-latest
    steps:
      - name: Muestra mensaje Hola mundo
        run: echo "Hola mundo, David"
        
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Listar los archivos del respositorio
        run: |
          echo "El repositorio ${{ github.repository }} contiene los siguientes archivos:"
          tree
