name: Variables

on:
  workflow_dispatch:

env:
  variable_global: VARIABLE GLOBAL

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      variable_job: VARIABLE JOB
    steps: 
      - name: step 1 del job-1
        run: |
          echo el valor de la variable globlal es: $variable_global
          echo 'Otra forma de escribir la variable es: ${{ env.variable_global }}'
          echo 'Tambien podemos definir variables a nivel de un unico job: ${{ env.variable_job }}'
          echo 'o Variables a nivel de step como esta: ${{ env.variable_step }}'
        env:
          variable_step: VARIABLE STEP

      - name: step 2 del job-1
        run: |
          echo 'seguimos con acceso al valor de la variable global ${{ env.variable_global }}'
          echo 'seguimos con acceso al valor de la variable del job ${{ env.variable_job }}'

  job-2:
    runs-on: ubuntu-latest
    steps: 
      - name: step 1 del job 2
        run: |
          echo 'seguimos con acceso al valor de la variable global: ${{ env.variable_global }}'
